### ISSUE TITLE
License for Use

### ISSUE THREAD

**Issue by seesemichaelj** [iammatthias/.com#66]
Hello Matthias,

I noticed your website has no license and all rights are reserved; it's a fantastic photography website that would definitely love to reuse for personal portfolio website.

Is there any thoughts as to whether or not you'd like to open the license at all to allow others to use the source?

100% understand if not! Figured I'd ask.

Thanks!

**Comment by iammatthias** [comment]
I’ve gone back an forth on this. 

In general, I don’t mind if people use this repo as a resource. Looking at code from other people was instrumental in developing this site, it wouldn’t exist without the open source community. 

That said, I’ve had a few issues with people passing my work off as their own. If someone wants to fork the repo and use it for a project of their own, great! But it bothers me when I then see those sites submitted to various showcases or “Awesome Lists” as original content. 

I may change my mind regarding a license sometime in the future(I generally try to stick with an MIT license), but for the time being I am content with enforcing a copyright notice while leaving the codebase open as a potential reference/resource. 

I don’t mind answering questions, and would be happy to help if you want to build something similar. But at the end of the day, this was built to be my personal portfolio site.

**Comment by seesemichaelj** [comment]
No worries, thanks for the response!

**Comment by jpvalery** [comment]
@iammatthias hope I didn't inadvertently fall in that category 😱

I originally put it on Gatsby Showcase because I felt changes were significant enough and credit obvious enough that it wouldn't be a problem. 
(And I saw it pop on gatsbyawesome.com but i think this is something automatic from someone scraping github). 

I really appreciated you sharing this and helping me rebuild my portfolio and definitely don't want to turn that into a sour experience 😢

**Comment by iammatthias** [comment]
Hey @jpvalery—no, it wasn’t you! And for the record, I’ve really enjoyed seeing what you did with the codebase. 

Like I said in my earlier comment—the decision to remove the license and add the copyright stemmed from a few people passing this off as their own. I guess I can break it down like this: 

- good: when you used the code as a reference you dove in and started wrenching on it to make it your own, pushed some fixes back my way, and then you left a shout-out in the ReadMe(and if I remember correctly, in your blog as well!) 
- bad: someone else claimed to be a full-stack dev, then cloned this into a clean repo before changed a few colors, then posted it on Reddit as “their new, custom portfolio”. 

I don’t mind if people use this code as a base, or if they fork it or clone it or whatever. The code is open on GitHub because I believe it is valuable to share that information. The copyright is really just peace of mind while I evaluate different potential license options.

**Comment by jpvalery** [comment]
Whew 😌 I was afraid for a sec to have overstepped haha!

Really dig the latest changes btw! I like to check in once in a while and see where this portfolio is growing to :)

**Comment by iammatthias** [comment]
I check yours out as well! It actually inspired me to add CodeClimate and Codacy to mine, really helped clean up some of the merges.

**Comment by iammatthias** [comment]
Small update: I have amended the copyright statement to only pertain to the the content (images, blog posts, etc). 

Code is public, always has been(this repo was never private, it could always be forked if someone wanted to), but is provided with limited-to-no support.

**Comment by sgorki** [comment]
So can i use it for my blog?

**Comment by iammatthias** [comment]
@sgorki Check the readme. I do not encourage using this as a starter or a theme, and I do not provide support for those that choose to do so. 

Nothing is stopping you from using the repo, the code is public, but to be perfectly frank there are better repos to use as a starter. This is not , especially for a blog, the blog functionality is extremely secondary and lacks basic functionality. The repo is extremely tailored to my personal use case. 

[GCN](https://github.com/ryanwiemer/gatsby-starter-gcn) is a fantastic Gatsby/Contentful starter that would be a better choice than this repo.
